### ISSUE TITLE
При лайке от двух разных пользователей на одно мероприятие при создании запроса GET events/?liked=true от токена второго по последовательности пользователя, в ответе приходит id и дата лайка предыдущего (первого) пользователя

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#100]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/

**Шаги воспроизведения:**
1.	создать пользователя 1, получить токен
2.	создать пользователя 2, получить токен
3.	создать мероприятие от имени HR 
4.	поставить лайк данному мероприятию под токеном пользователя 1 POST/socials/likes/
в теле ответа 
{
    "id": 15,
    "created": "2023-06-26T21:20:44.111249+03:00",
    "event": 10,
    "entry": null
}

5.	поставить лайк данному мероприятию под токеном пользователя 2 POST/socials/likes/ 
в теле ответа 
{
    "id": 16,
    "created": "2023-06-26T21:21:25.378914+03:00",
    "event": 10,
    "entry": null
}

6.	сделать запрос GET events/?liked=true под токеном пользователя 1 посмотреть ответ 
7.	сделать запрос GET events/?liked=true под токеном пользователя 2 посмотреть ответ 

**Фактический результат:** 

При запросе GET events/?liked=true под токеном пользователя 2 получаем в ответе id  15 и дату лайка на мероприятие от пользователя 1
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 10,
            "liked": {
                "id": 15,
                "created": "2023-06-26T21:20:44.111249+03:00"
            },
            "author": {
                "id": 2,
                "first_name": "Елена",
                "last_name": "Дмитриева",
                "avatar": null,
                "avatar_full": null
            },
            "name": "Большая it Корпоративка",
            "for_all": false,
            "text": "Большая it Корпоративка",
            "created": "2023-06-26T21:16:24.782463+03:00",
            "start_time": "2023-06-26T22:30:11.246000+03:00",
            "end_time": "2023-06-27T01:00:11.246000+03:00",
            "departments": [
                3
            ],
            "employees": [
                7
            ]
        }
    ]
}

**Ожидаемый результат:**

При запросе GET events/?liked=true под токеном пользователя 2 получаем в ответе id  16 и дату лайка на мероприятие от пользователя 2

**Comment by AleksandrUsolcev** [comment]
https://github.com/moodbeat/back/pull/8

**Comment by QA-Aleksandra** [comment]
результат ре-теста: баг исправлен, закрываю
