### ISSUE TITLE
201 Created вместо 400 Bad Request при отправке запроса POST /users/register/ при вводе в "first_name" пробела в конце имени

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#12]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/
**Предусловие:**
Создать ссылку-приглашение на почту POST /users/send_invite/
**Шаги воспроизведения:**
Отправить POST /users/register/ на регистрацию пользователя с пробелом в конце имени "first_name": "Анна "
В теле указать:
{
  "invite_code": "NDA4ZTMyNDMtNDhhMC00MmJhLWE5NzctOTQyNzU4ZWFlOTJkPPs2hvM610bwW6pUvlIsg5emT+s2nTXD2vdt2ZPT9I8=",
  "first_name": "Анна ",
  "last_name": "Иванова",
  "password": "1FbJkResPh",
  "password_confirm": "1FbJkResPh",
  "department": 1,
  "position": 1
}
**Фактический результат:**
201 Created. Есть создание в базе данных.

**Ожидаемый результат:**
400 Bad Request. Нет создания в базе данных.

**Comment by AleksandrUsolcev** [comment]
Это не баг а фича)
