### ISSUE TITLE
201 Created вместо 400 Bad Request при отправке запроса POST /users/register/ при вводе в "first_name" цифр

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#15]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/
**Предусловие:**
Создать ссылку-приглашение на почту POST /users/send_invite/

**Шаги воспроизведения:**

Отправить POST /users/register/ на регистрацию пользователя с цифрами в имени "first_name": "Костя345"
В теле указать:
{
  "invite_code": "YzE4NTM1MzItMzk3ZC00ZmYwLTlkMDEtZmUzYzNlYjQ0NjM5PPs2hvM610bwW6pUvlIsg5emT+s2nTXD2vdt2ZPT9I8=",
  "first_name": "Костя345",
  "last_name": "Иванов",
  "password": "1FbJkResPh",
  "password_confirm": "1FbJkResPh",
  "department": 1,
  "position": 1
}
**Фактический результат:**
201 Created. Есть создание в базе данных.

**Ожидаемый результат:**
400 Bad Request. Нет создания в базе данных.

**Comment by AleksandrUsolcev** [comment]
https://github.com/pervukhina-anna/employee_mood_backend/commit/d0e0a4e0be0c117ac91db9f4edd73e83117a9674
