### ISSUE TITLE
201 Created вместо 400 Bad Request при отправке запроса POST /users/register/ "password" принимает пробел в начале

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#19]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/
**Предусловие:**
Создать ссылку-приглашение на почту POST /users/send_invite/
**Шаги воспроизведения:**
Отправить POST /users/register/ на регистрацию пользователя с пробелом в начале пароля "password ": “ FbJkResDnPh”

В теле указать:
{
  "invite_code": "N2MyODNlNWMtNmFlZC00NzY2LWI1N2QtODgwYTcyNDNhYWU1PPs2hvM610bwW6pUvlIsg5emT+s2nTXD2vdt2ZPT9I8=",
  "first_name": "Борис",
  "last_name": "Иванов",
  "password": " FbJkResDnPh",
  "password_confirm": " FbJkResDnPh",
  "department": 1,
  "position": 1
}
**Фактический результат:**
201 Created. Есть создание в базе данных.

**Ожидаемый результат:**
400 Bad Request. Нет создания в базе данных.

**Comment by AleksandrUsolcev** [comment]
Это не баг а фича)
