### ISSUE TITLE
200 OK вместо 400 Bad Request при отправке запроса POST users/send_invite/ при вводе в "email" 7 символов, 6 символов

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#25]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/

**Шаги воспроизведения:**
1. Отправить POST users/send_invite/ с введенным в "email" 7 символов

2. В теле указать:
{
  "email": "l@al.ru"
}
3. Удалить тело запроса 
4. Отправить POST users/send_invite/ с введенным в "email" 6 символов
5. в теле указать: 
{
  "email": "l@l.ru"
}

**Фактический результат:**
200 ОК. 
{
    "detail": "Ссылка для регистрации отправлена на email",
    "invite_code": "ZDRlODQ5NDItNDA2NC00OGUxLTlkYWYtMGNlM2I4ZDI2YmVkPPs2hvM610bwW6pUvlIsg5emT+s2nTXD2vdt2ZPT9I8="
}
**Ожидаемый результат:**
400 Bad Request.

**Comment by AleksandrUsolcev** [comment]
https://github.com/pervukhina-anna/employee_mood_backend/commit/40bb0038ff68b437ba170fbe207fea3a868fb9a1
