### ISSUE TITLE
200 OK вместо 400 Bad Request при отправке запроса при отправке запроса POST users/send_invite/ при вводе в "email" 6 символов

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#26]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/
**Предусловие:**
Создать ссылку-приглашение на почту POST /users/send_invite/
**Шаги воспроизведения:**
Отправить POST users/send_invite/ с введенным в "email" 6 символов

В теле указать:
{
  "email": "l@l.ru"
}
**Фактический результат:**
200 ОК. 
{
    "detail": "Ссылка для регистрации отправлена на email",
    "invite_code": "YTJjNGM5OTgtZDAwZi00ODQ0LWE4OWItYzBlNjNiNzM0YmI3PPs2hvM610bwW6pUvlIsg5emT+s2nTXD2vdt2ZPT9I8="
}
**Ожидаемый результат:**
400 Bad Request.

**Comment by AleksandrUsolcev** [comment]
https://github.com/pervukhina-anna/employee_mood_backend/commit/40bb0038ff68b437ba170fbe207fea3a868fb9a1
