### ISSUE TITLE
200 OK вместо 400 Bad Request при отправке запроса POST users/send_invite/ при вводе в "email" букв русского алфавита, букв другого алфавита в доменном имени, спец. символы в имени пользователя

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#27]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/

**Шаги воспроизведения:**
1. Отправить POST users/send_invite/ с введенным в "email" букв русского алфавита в доменном имени

2. В теле указать:
{
  "email": "alex@алекс.ру"
}
3. Удалить тело запроса 
4. Отправить POST users/send_invite/ с введенным в "email" букв другого алфавита в доменном имени 
5. в теле указать: 
{
  "email": "aleks@コンスタンチン.ru"
}
6. Удалить тело запроса
7. Отправить POST users/send_invite/ с введенным в "email" спец. символами в имени пользователя 
8. В теле указать: 
9. {
  "email": "!!!!????@aleks.ru"
}

**Фактический результат:**
200 ОК. 
{
    "detail": "Ссылка отправлена повторно",
    "invite_code": "Mzc4NjZkZDYtZTBjNi00ZjY3LWI1ODktNWY2ZDFlNmJhYjIxPPs2hvM610bwW6pUvlIsg5emT+s2nTXD2vdt2ZPT9I8="
}
**Ожидаемый результат:**
400 Bad Request.

**Comment by AleksandrUsolcev** [comment]
https://github.com/pervukhina-anna/employee_mood_backend/commit/d163d5c69596de5671e1af2dc2e6f794009594d6
