### ISSUE TITLE
Статус 404 при изменении пароля текущего пользователя (HR)

### ISSUE THREAD

**Issue by ilnarnaril** [AcceleratorYandexPracticum/employee_mood#34]
Окружение:
https://em-test.usolcev.com/api/v1/swagger/
Предусловие:
Авторизоваться HR
Шаги:
Отправить запрос на POST/users/password/change
Тело:
{
  "current_password": "HRexamplePass123",
  "new_password": "HRexamplePass555",
  "new_password_confirm": "HRexamplePass555"
}

ФР:
Статус 404
Ответ:
<!doctype html>
<html lang="en">
<head>
    <title>Not Found</title>
</head>
<body>
    <h1>Not Found</h1>
    <p>The requested resource was not found on this server.</p>
</body>
</html>

ОР:
Статус 200 ОК

**Comment by ilnarnaril** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132495850/9bdfcef5-cf80-436e-93ca-9ac062c215a0)

**Comment by AleksandrUsolcev** [comment]
Тут адрес эндпоинта неверный, нужен users/password_change, а не users/password/change (как на скрине)

**Comment by AleksandrUsolcev** [comment]
Мой косяк в документации, поменял

**Comment by ilnarnaril** [comment]
Ок. Принял
