### ISSUE TITLE
404Not Found вместо 204 No Content при отправке запроса DELETE /departments/9 Возвращает - "detail": "Страница не найдена."

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#35]
Окружение:
https://em-test.usolcev.com/api/v1/swagger/
Предусловие:
Создать отдел с id 9 POST/departments
Шаги воспроизведения:
Отправить DELETE /departments/9 на удаление

Ожидаемый результат:
204 No Content. Отдел удаляется из Базы данных.

Фактический результат:
404Not Found. "detail": "Страница не найдена."

**Comment by AleksandrUsolcev** [comment]
fixed

https://github.com/pervukhina-anna/employee_mood_backend/commit/c0103d92cdaaa34481eccfb6d28db032a709d978
