### ISSUE TITLE
404Not Found вместо 200 OK при отправке запроса GET /departments/9 Возвращает - "detail": "Страница не найдена."

### ISSUE THREAD

**Issue by Lena-Muzika** [AcceleratorYandexPracticum/employee_mood#36]
Окружение:
https://em-test.usolcev.com/api/v1/swagger/
Предусловие:
Создать отдел с id 9 POST/departments
Шаги воспроизведения:
Отправить GET /departments/9 на возвращение
Ожидаемый результат:
200 OK. Отдел возвращается из Базы данных.
Фактический результат:
404Not Found. "detail": "Страница не найдена."

**Comment by AleksandrUsolcev** [comment]
fixed

https://github.com/pervukhina-anna/employee_mood_backend/commit/c0103d92cdaaa34481eccfb6d28db032a709d978
