### ISSUE TITLE
Выпадающий список отделов при регистрации сотрудника работает после нескольких обновлений страницы

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#42]
**Предусловие:**
1.	Создать ссылку-приглашение на почту POST /users/send_invite/
2.	Вставить invite в URL
3.	Обновить страницу

**Шаги воспроизведения:**
1.Заполнить поле Имя: Иван
2.Заполнить поле Фамилия: Иванов
3.Нажать на выпадающий список отделов

**Фактический результат:**
Список отделов не подгружается. Вместо списка: No options.
При нескольких обновлениях страницы список отделов подгружается. 

**Ожидаемый результат:**
Можно выбрать отдел.

**Окружение:** 
Браузер: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows
Браузер: Яндекс.Браузер 23.5.0.2271 (64-bit) разрешение 1366x768, ОС: Windows 

Серьезность бага: Критический

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/14f54764-7820-4249-b764-68c2fa486d24)

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/9c0ac59d-f46d-4987-abce-d61735ea70d8)

**Comment by AnaSerg** [comment]
@QA-Aleksandra исправила, теперь сначала подгружается инвайт-код, и только после этого вся страница с выпадающими списками @acaee8a
