### ISSUE TITLE
201 Created вместо 400 Bad Request при отправке запроса POST /users/register/ "password" принимает буквы другого алфавита+ буквы верхнего и нижнего регистра

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#44]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/
**Предусловие:**
Создать ссылку-приглашение на почту POST /users/send_invite/

**Шаги воспроизведения:**
Отправить POST /users/register/ на регистрацию пользователя другим типом данный в "password": 12345
В теле указать:
{
  "invite_code": "NTIxNTI1M2YtODVhZi00YjY2LTljMGUtNDhlZTAwMDQwYjMzTVGxITGXfGCuJ3+P6dqLOMfQ7Qd+XFPFGts7T3obPSc=",
  "first_name": "Иван",
  "last_name": "Иванов",
  "department": 7,
  "position": 2,
  "password": "コンスタンチンコンスタンチンTr",
  "password_confirm": "コンスタンチンコンスタンチンTr"
}

**Фактический результат:**
201 Created. 
**Ожидаемый результат:**
400 Bad Request.

**Comment by AleksandrUsolcev** [comment]
https://github.com/pervukhina-anna/employee_mood_backend/commit/b35daed09228a1708a74beb4158a75f9a0dbdcb0
