### ISSUE TITLE
При регистрации поле Пароль принимает пробел в середине, когда фокус уходит с поля, нет надписи «Пароль не соответствует требованиям»

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#45]
**Предусловие:**
1.	Создать ссылку-приглашение на почту POST /users/send_invite/
2.	Вставить invite в URL
3.	Обновить страницу

**Шаги воспроизведения:**
1.Заполнить поле Имя: Иван
2.Заполнить поле Фамилия: Иванов
3.Выбрать отдел из списка: Отдела маркетинга 
4.Выбрать должность: Менеджер
5.Заполнить поле Пароль с пробелом в середине: FbJkR esDnPh
6.Снять фокус с поля
7.Заполнить поле Подтверждение пароля с пробелом в середине: FbJkR esDnPh
8. Снять фокус с поля

**Фактический результат:**
Рамка поля и поле не подсвечивается красным, нет надписи «Пароль не соответствует требованиям»

**Ожидаемый результат:**
Рамка поля и поле подсвечивается красным, есть надпись «Пароль не соответствует требованиям»

Окружение: 
Браузер: Chrome 113.0.5672.127 (64-bit), разрешение 1920х1080, ОС: Windows
Браузер: Яндекс.Браузер 23.5.0.2271 (64-bit), разрешение 1366x768, ОС: Windows

**Comment by AnaSerg** [comment]
@QA-Aleksandra Поменяла регулярное выражение для валидации, как на бэкенде [1d804e8](https://github.com/dev0x451/employee_mood_frontend/pull/32/commits/1d804e84f6d9689616848edfb9144d7683788955)](https://github.com/dev0x451/employee_mood_frontend/pull/32/commits/1d804e84f6d9689616848edfb9144d7683788955)
