### ISSUE TITLE
При отправке запроса POST/metrics/results/ при положительных ответах 7 результат в теле ответа "result": "Тревожное", вместо ”В группе риска”

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#48]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/

**Шаги воспроизведения:**
1. Отправить запрос на получение приглашения POST https://em-test.usolcev.com/api/v1/users/send_invite
в теле указать {
  "email": "alek212@aleks.ru"
}

2. Отправить запрос на регистрацию пользователя POST/https://em-test.usolcev.com/api/v1/users/register/ с invite_code"  из шага 1
3. Создать токен для пользователя POST https://em-test.usolcev.com/api/v1/auth/jwt/create/ с {
  "email" и "password" из регистрации
4. Отправить запрос для добавления результатов пройденного опроса POST https://em-test.usolcev.com/api/v1/metrics/results/
В теле указать:
{
  "positive_value": 7,
  "negative_value": 3,
  "survey": 1
}

**Фактический результат:**
201Created
{
    "id": 2,
    "result": "Тревожное",
    "completion_date": "2023-05-31",
    "next_attempt_date": "2023-06-30",
    "employee": 26,
    "survey": 1
}
**Ожидаемый результат:**
201Created "result": "В группе риска"

Серьезность бага: Major

**Comment by AleksandrUsolcev** [comment]
https://github.com/pervukhina-anna/employee_mood_backend/commit/1ed1568ede6711b1be25a0d646ec6632d7e63adb
