### ISSUE TITLE
На странице Тест наименование сортировки «Результат» выровнено по центру поля

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#51]
**Предусловие:**
1.	Создать ссылку-приглашение на почту POST /users/send_invite/
2.	Вставить invite в URL
3.	Обновить страницу
**Шаги воспроизведения:**
1.Зарегистироваться 
2.Нажать на вкладку Тест 

**Фактический результат:**
На странице Тест наименование сортировки Результат выровнено по центру поля 
**Ожидаемый результат:**
На странице Тест наименование сортировки Результат выровнено относительно результатов теста
**Окружение:** 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.

Серьезность бага: Тривиальный

**Comment by RomanRiyanov** [comment]
Исправлено, выровнено по столбцу с результатами

**Comment by RomanRiyanov** [comment]
Исправлено, выровнено по столбцу с результатами
