### ISSUE TITLE
На странице Тест рядом с результатами тестирования нет иконки в виде эллипса

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#52]
На странице Тест рядом с результатами тестирования в процентах нет иконки в виде эллипса
**Предусловие:**
1.	Создать ссылку-приглашение на почту POST /users/send_invite/
2.	Вставить invite в URL
3.	Обновить страницу
**Шаги воспроизведения:**

1.Зарегистироваться 
2.Нажать на вкладку Тест 

**Фактический результат:**
На странице Тест рядом с результатами тестирования нет иконки в виде эллипса
**Ожидаемый результат:**
На странице Тест рядом с результатами тестирования есть иконки в виде эллипса
**Окружение:** 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.

Серьезность бага: Тривиальный

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/06432907-0aa0-4c51-8749-520e22eb09d0)

**Comment by RomanRiyanov** [comment]
Проценты убраны, логика эллипса-светофора готова, её можно увидеть на вкладке с результатами теста.
Чуть позже будет добавлен суда и закрыт баг
