### ISSUE TITLE
На странице Тест рядом с результатами тестирования есть проценты, пройденного теста

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#53]
**Предусловие:**
1.	Создать ссылку-приглашение на почту POST /users/send_invite/
2.	Вставить invite в URL
3.	Обновить страницу
**Шаги воспроизведения:**
1.Зарегистироваться 
2.Нажать на вкладку Тест 

**Фактический результат:**
На странице Тест рядом с результатами тестирования есть проценты, пройденного теста 
**Ожидаемый результат:**
На странице Тест рядом с результатами тестирования есть только эллипс и результат пройденного теста (Нормальное, Тревожное, В группе риска)
**Окружение:** 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.

**Comment by QA-Aleksandra** [comment]
Макет 


![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/f27d8fdd-0d7b-48b5-aa36-14d4e067f3aa)

**Comment by RomanRiyanov** [comment]
Проценты убраны, логика эллипса-светофора готова, её можно увидеть на вкладке с результатами теста. 
Чуть позже будет добавлен суда и закрыт баг

**Comment by RomanRiyanov** [comment]
Проценты убраны, логика эллипса-светофора готова, её можно увидеть на вкладке с результатами теста.
Баг с процентами закрываю
