### ISSUE TITLE
!! После клика по кнопке Пройти тест из Главной при закрытии, открывшегося Теста происходит переход на страницу авторизации, происходит выход из приложения, вместо перехода обратно на Главную

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#54]
**Предусловие:**
1.	Создать ссылку-приглашение на почту POST /users/send_invite/
2.	Вставить invite в URL
3.	Обновить страницу
**Шаги воспроизведения**:
1.Зарегистироваться 
2.Нажать на кнопку Пройти тест на Главной странице
3.Закрыть тест через крестик 

**Фактический результат:**
После клика по кнопке Пройти тест из Главной при закрытии, открывшегося Теста происходит переход на страницу авторизации, происходит выход из приложения
**Ожидаемый результат:**
После клика по кнопке Пройти тест из Главной при закрытии, открывшегося Теста происходит переход на обратно на Главную
**Окружение:** 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.

Серьезность бага: Критический

**Comment by QA-Aleksandra** [comment]
https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/28864625-2878-4845-aff8-af7e88a3deeb

**Comment by RomanRiyanov** [comment]
Баг исправлен
