### ISSUE TITLE
После клика по кнопке Пройти тест из Главной после прохождения теста при нажатии на кнопку Закрыть на странице с результатами теста, происходит переход на страницу Тесты

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#55]
**Предусловие:**
1.	Создать ссылку-приглашение на почту POST /users/send_invite/
2.	Вставить invite в URL
3.	Обновить страницу
**Шаги воспроизведения:**
1.Зарегистироваться 
2.Нажать на кнопку Пройти тест на Главной странице
3.Пройти тест
4.Нажать на кнопку Закрыть на странице с результатами теста 

**Фактический результат:**
После клика по кнопке Пройти тест из Главной после прохождения теста при нажатии на кнопку Закрыть на странице с результатами теста, происходит переход на страницу Тесты
**Ожидаемый результат:**
После клика по кнопке Пройти тест из Главной после прохождения теста при нажатии на кнопку Закрыть на странице с результатами теста, происходит переход на Главную
п.4.9 Требований
Окружение: 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.

Серьезность бага: Минорный

**Comment by RomanRiyanov** [comment]
Баг исправлен, после клика переход осуществляется на ГЛАВНУЮ
