### ISSUE TITLE
!! При клике по кнопке Подробнее для просмотра результатов теста на странице Тест, при закрытии через крестик происходит переход на страницу авторизации, вместо возврата на страницу Тест

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#56]
**Предусловие:**
1.	Создать ссылку-приглашение на почту POST /users/send_invite/
2.	Вставить invite в URL
3.	Обновить страницу
**Шаги воспроизведения:**
1.Зарегистироваться 
2.Перейти на вкладку Тест
3.Нажать на кнопку Пройти тест
4.Пройти тест
5.Нажать на кнопку Закрыть
6. Нажать кнопку Подробнее
7. Закрыть страницу с результатами теста через крестик

**Фактический результат:**
При клике по кнопке Подробнее для просмотра результатов теста на странице Тест, при закрытии через крестик происходит переход на страницу авторизации
**Ожидаемый результат:**
При клике по кнопке Подробнее для просмотра результатов теста на странице Тест, при закрытии через крестик происходит возврат на страницу Тест
**Окружение:** 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.

Серьезность бага: Критический

**Comment by RomanRiyanov** [comment]
Баг исправлен, бедный крестик работает как в ТЗ. Коммит будет в течение 10ти минут
