### ISSUE TITLE
!! При нажатии кнопку Пройти тест со страницы Тесты и закрыть через крестик, происходит переход на страницу авторизации, происходит выход из приложения

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#57]
**Предусловие:**
1.	Создать ссылку-приглашение на почту POST /users/send_invite/
2.	Вставить invite в URL
3.	Обновить страницу
**Шаги воспроизведения:**
1.Зарегистироваться 
2.Перейти на вкладку Тест
3.Нажать на кнопку Пройти тест
4.Нажать на крестик 

**Фактический результат:**
При нажатии кнопку Пройти тест со страницы Тесты и закрыть через крестик, происходит переход на страницу авторизации, происходит выход из приложения
**Ожидаемый результат:**
При нажатии кнопку Пройти тест со страницы Тесты и закрыть через крестик, будет возврат на страницу Тесты
**Окружение:** 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.

Серьезность бага: Критический

**Comment by RomanRiyanov** [comment]
Баг исправлен, бедный крестик работает как в ТЗ. Коммит будет в течение 10ти минут

**Comment by QA-Aleksandra** [comment]
Итог ре-теста: Сейчас идет возврат на главную, вместо на страницу Тест. 
Вкладка тесты- Пройти тест - Закрываем по крестику - должен быть возврат обратно на страницу с которой начинали те на страницу Тест

Аналогично если пройти тест из вкладки Тест, нажать на Закрыть или крестик на результате теста - идет возврат на главную, вместо возврата к прежней странице Тест
