### ISSUE TITLE
Ошибка 500 Internal Server Error вместо 400 Bad Request при отправке запроса POST /users/register/ при вводе в "first_name" 33 символа

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#6]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/
**Предусловие:**
Создать ссылку-приглашение на почту POST /users/send_invite/
**Шаги воспроизведения:**
Отправить POST /users/register/ на регистрацию пользователя с введенным в "first_name": "Константинконстантинконстантинкаа" 33 символа
В теле указать:
{
  "invite_code": "NDU3YmM2NDEtZjM0ZS00NzcxLWI1YzMtNzFkMjY4N2U2MmFlPPs2hvM610bwW6pUvlIsg5emT+s2nTXD2vdt2ZPT9I8=",
  "first_name": "Константинконстантинконстантинкаа",
  "last_name": "Иванов",
  "password": "1FbJkResPh",
  "password_confirm": "1FbJkResPh",
  "department": 1,
  "position": 1
}
**Фактический результат:**
500 Internal Server Error 
<!doctype html>
<html lang="en">

<head>
	<title>Server Error (500)</title>
</head>

<body>
	<h1>Server Error (500)</h1>
	<p></p>
</body>

</html> 
**Ожидаемый результат:**
400 Bad Request

**Comment by AleksandrUsolcev** [comment]
https://github.com/pervukhina-anna/employee_mood_backend/commit/d0e0a4e0be0c117ac91db9f4edd73e83117a9674
