### ISSUE TITLE
В результатах теста результат отображается «Нормальное состояние» вместо «нормальное» как на макетах

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#66]
**Предусловие:**
1.	Создать ссылку-приглашение на почту POST /users/send_invite/
2.	Вставить invite в URL
3.	Обновить страницу
**Шаги воспроизведения:**
1.Зарегистироваться 
2.Перейти на вкладку Тест
3.Нажать на кнопку Пройти тест
4. Пройти тест отметив все ответы Нет
5. Посмотреть отображение результата теста 
**Фактический результат:**
В результатах теста результат отображается «Нормальное состояние» вместо «нормальное» как на макетах 

**Ожидаемый результат:**
В результатах теста результат отображается состояние: нормальное 

Окружение: 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Тривиальный

**Comment by RomanRiyanov** [comment]
Данные для отображения приходят с сервера, будет обсуждение с командой бекэнда и после этого исправление
