### ISSUE TITLE
Не верное отображение кол-ва сотрудников на странице Моя команда

### ISSUE THREAD

**Issue by SilexDS** [AcceleratorYandexPracticum/employee_mood#73]
**Предусловие**
1. Открыть веб-приложение Настроение сотрудника.
2. Войти под учетной записью HR. 
логин: hr@example.com
пароль: HRexamplePass123
3. Прейти на страницу Моя команда.

**Шаги воспроизведения**
Посмотреть список сотрудников. 

**ОР**
На странице помещается 10 сотрудников.
ТЗ п.5.4.2.3 Когда список сотрудников не помещается на страницу, появляется возможность бесконечной прокрутки. Максимальное количество сотрудников на странице 10 штук. 

**ФР**
Все сотрудники отображены на экране.

**Окружение**
Браузер:Яндекс Браузер v.23.5.1.714, разрешение: 1920х1080;
ОС: Windows 10 Pro v.22H2 сборка 19045.2965

![Image](https://user-images.githubusercontent.com/75949652/243351650-37f79a64-fc0c-428a-8b1e-2dbc3a1a2913.jpg)

![Image](https://user-images.githubusercontent.com/75949652/243351711-3b5b730a-e471-4fd5-96ca-fc2abfda15a7.jpg)

**Comment by AnaSerg** [comment]
@SilexDS исправили. Теперь на странице при загрузке отображается 6 сотрудников (по ТЗ). По нажатию на кнопку отображается еще 6 и так далее
