### ISSUE TITLE
Ошибка в написание слова e-mail на странице добавления сотрудника

### ISSUE THREAD

**Issue by SilexDS** [AcceleratorYandexPracticum/employee_mood#76]
**Предусловие**
1. Открыть веб-приложение Настроение сотрудника.
2. Войти под учетной записью HR. 
логин: hr@example.com
пароль: HRexamplePass123
3. Прейти на страницу Моя команда.

**Шаги воспроизведения**
Нажать на кнопку "+ Добавить сотрудника"

**ОР**
Над полем ввода надпись "Введите e-mail"

**ФР**
Над полем ввода надпись "Введите email"

**Окружение**
Браузер:Яндекс Браузер v.23.5.1.714, разрешение: 1920х1080;
ОС: Windows 10 Pro v.22H2 сборка 19045.2965

![Image](https://user-images.githubusercontent.com/75949652/243352806-a15e4040-f637-4622-901b-1d99f44e4ecf.jpg)

![Image](https://user-images.githubusercontent.com/75949652/243352839-47a6624f-3811-4063-9991-010f74805400.jpg)

**Comment by AnaSerg** [comment]
@SilexDS исправлено)
<img width="411" alt="Снимок экрана 2023-06-13 в 14 14 36" src="https://github.com/AcceleratorYandexPracticum/employee_mood/assets/91882066/d413f6a5-48a4-4b78-8d9f-566bbe063893">
