### ISSUE TITLE
Расположение элементов статей не соответствует макету на странице Моя команда

### ISSUE THREAD

**Issue by SilexDS** [AcceleratorYandexPracticum/employee_mood#77]
**Предусловие**
1. Открыть веб-приложение Настроение сотрудника.
2. Войти под учетной записью HR. 
логин: hr@example.com
пароль: HRexamplePass123
3. Прейти на страницу Моя команда.

**Шаги воспроизведения**
Справой стороны расположены элементы статей.

**ОР**
Расположение текста и статей соответствуют макету.

**ФР**
Расположение текста и статей не соответствуют макету.

**Окружение**
Браузер:Яндекс Браузер v.23.5.1.714, разрешение: 1920х1080;
ОС: Windows 10 Pro v.22H2 сборка 19045.2965

![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/75949652/da5f5b7c-74aa-4c12-ab30-3d5d4df34cbb)

![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/75949652/e822d4ba-a1db-4974-9535-904e690027d1)

**Comment by AnaSerg** [comment]
<img width="645" alt="Снимок экрана 2023-06-12 в 12 06 05" src="https://github.com/AcceleratorYandexPracticum/employee_mood/assets/91882066/2c9612cd-c017-470d-9d52-102db7552b0a">
@SilexDS исправили в Моя команда (на главной пока нет)

**Comment by AnaSerg** [comment]
В баг-репорте №78 та же история, это случайно продублировалось?
