### ISSUE TITLE
Расположение элементов статей не соответствует макету на странице Моя команда

### ISSUE THREAD

**Issue by SilexDS** [AcceleratorYandexPracticum/employee_mood#78]
**Предусловие**
1. Открыть веб-приложение Настроение сотрудника.
2. Войти под учетной записью HR. 
логин: hr@example.com
пароль: HRexamplePass123
3. Прейти на страницу Моя команда.

**Шаги воспроизведения**
Справой стороны расположены элементы статей.

**ОР**
Расположение текста и статей соответствуют макету.

**ФР**
Расположение текста и статей не соответствуют макету.

**Окружение**
Браузер:Яндекс Браузер v.23.5.1.714, разрешение: 1920х1080;
ОС: Windows 10 Pro v.22H2 сборка 19045.2965

![Image](https://user-images.githubusercontent.com/75949652/243353669-aa168a4a-77be-4934-8594-266982404462.jpg)

![Image](https://user-images.githubusercontent.com/75949652/243353687-0b55afde-230c-4c96-bced-55d9a7ece5ed.jpg)

**Comment by AnaSerg** [comment]
@SilexDS исправили по новому макету
<img width="400" alt="Снимок экрана 2023-06-25 в 03 32 58" src="https://github.com/AcceleratorYandexPracticum/employee_mood/assets/91882066/f01888f1-06f3-44ae-bd25-1e7d1f7b9e9f">

**Comment by AnaSerg** [comment]
Пока на ширине 1920 лучше не проверять, так как у нас нет адаптивов и мы пока сделали на свое усмотрение. Когда появятся адаптивы, будет и норм верстка) Предлагаю пока закрыть)
