### ISSUE TITLE
Серый цвет вводимых символов в поле имя на странице Моя команда

### ISSUE THREAD

**Issue by SilexDS** [AcceleratorYandexPracticum/employee_mood#81]
**Предусловие**
1. Открыть веб-приложение Настроение сотрудника.
2. Войти под учетной записью HR. 
логин: hr@example.com
пароль: HRexamplePass123
3. Прейти на страницу Моя команда.

**Шаги воспроизведения**
Ввести в поле "Начните вводить имя": иванов.

**ОР**
Вводимый цвет символов черный.

**ФР**
Вводимый цвет символов серый.

**Окружение**
Браузер:Яндекс Браузер v.23.5.1.714, разрешение: 1920х1080;
ОС: Windows 10 Pro v.22H2 сборка 19045.2965

![Image](https://user-images.githubusercontent.com/75949652/243359050-670604ef-ffb7-4b54-b0df-725c4887bc5f.jpg)

**Comment by AnaSerg** [comment]
@SilexDS исправили

<img width="498" alt="Снимок экрана 2023-06-25 в 03 30 30" src="https://github.com/AcceleratorYandexPracticum/employee_mood/assets/91882066/a7971cd3-e9d8-41e2-a8e9-05c41e4e6370">
