### ISSUE TITLE
При входе под ролью руководитель, HR, при клике по вкладке Моя команда отображается белый экран

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#82]
**Шаги воспроизведения:**
1.Авторизоваться в приложении под ролью HR 
2.Кликнуть по вкладке Моя команда
3.Разлогиниться через удаление jwt в Local Storage
4. Авторизоваться в приложении под ролью руководитель
5. Кликнуть по вкладке Моя команда
**Фактический результат:**
При входе под ролью руководитель, HR, при клике по вкладке Моя команда отображается белый экран

**Ожидаемый результат:**
При входе под ролью руководитель, HR, при клике по вкладке Моя команда страница  отображается 
**Окружение:** 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Критический

**Comment by QA-Aleksandra** [comment]
https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/fd4f7e80-b69f-41de-8043-f0277cfa5299

**Comment by AnaSerg** [comment]
@QA-Aleksandra исправили баг. Проблема была в том, что на бэке поменялся формат данных, относящихся к пользователю, а мы обрабатывали по-старому.
