### ISSUE TITLE
При сортировке по дате смещается дата с двузначным числом

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#83]
**Шаги воспроизведения:**
1.Авторизоваться в приложении под ролью HR 
2.Кликнуть по вкладке Тесты
3.Нажать на сортировку по дате
**Фактический результат:**
При сортировке по дате смещается дата с двузначным числом 

**Ожидаемый результат:**
При сортировке по дате есть единое выравнивание в столбце 
**Окружение:** 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Тривиальный

**Comment by QA-Aleksandra** [comment]
https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/ef807d79-4d8e-46f2-abdd-582be04c3d03

**Comment by QA-Aleksandra** [comment]
А если год и месяц закрепить, чтобы при дате с двузначным числом они не смещались, может этот столбец сделать по правому?

**Comment by AnaSerg** [comment]
@QA-Aleksandra это очень костыльное решение получится(
и я не уверена, что оно стоит того. У нас дата приходит целым форматом, нам мало того, что нужно будет городить верстку, чтобы сделать 2 столбика, которые будут смотреться как один. Так еще надо будет дербанить дату, чтобы цифра пошла в один столбик, а все остальное в другой

Нужно ли нам это?
Кода придется написать много, очень некрасивого))
