### ISSUE TITLE
В форме регистрации нет плейсхолдера у поля Имя и Фамилия

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#85]
**Шаги воспроизведения:**
1.Зайти на страницу Регистрации https://mood-beap.netlify.app/register 

**Фактический результат:**
В форме регистрации нет плейсхолдера у поля Имя и Фамилия 

**Ожидаемый результат:**
В форме регистрации есть плейсхолдер у поля Имя и Фамилия 
**Окружение:** 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Серьёзность бага: Тривиальный

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/516450e5-9897-4c21-bd8e-0758ec3c39f9)

**Comment by AnaSerg** [comment]
@QA-Aleksandra тут же вроде нет плейсхолдеров? Или я неправильно понимаю макеты.. В отделах и должностях они есть, чтобы было понятно, что надо щелкнуть на стрелочку

<img width="503" alt="Снимок экрана 2023-06-25 в 03 28 34" src="https://github.com/AcceleratorYandexPracticum/employee_mood/assets/91882066/268aae12-f3ea-493d-a950-d2336d6eb07c">

**Comment by QA-Aleksandra** [comment]
Пусть не будет, закрываю)
