### ISSUE TITLE
На странице Моя команда в форме добавления сотрудника кнопка Добавить активна, когда поле не заполнено

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#87]
**Шаги воспроизведения:**
1.	Авторизоваться от HR  
2.	Перейти на вкладку Моя команда
3.	Нажать Добавить сотрудника

**Фактический результат:**
На странице Моя команда в форме добавления сотрудника кнопка Добавить активна, когда поле не заполнено

**Ожидаемый результат:**
На странице Моя команда в форме добавления сотрудника кнопка Добавить не активна, когда поле не заполнено

Окружение: 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Тривиальный

**Comment by QA-Aleksandra** [comment]
Макет
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/4879be89-429c-446d-a220-9c778841dc88)
Реализация
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/0e413489-6a2f-4454-b3a3-ff0fadedf6cc)

**Comment by AnaSerg** [comment]
@QA-Aleksandra исправили
<img width="632" alt="Снимок экрана 2023-06-25 в 03 31 53" src="https://github.com/AcceleratorYandexPracticum/employee_mood/assets/91882066/884d748a-bbfe-4a28-bc4c-e906fb674127">
