### ISSUE TITLE
Если в опроснике профессионального выгорания Маслач нажать Назад, окно опроса сворачивается в некликабельное окно, при последующим нажатии в этом окне на кнопку Назад вопросы появляются в обратном порядке с отрицательным числом в шкале, начиная с 21 вопроса (На работе я спокойно справляюсь с эмоциональными проблемами), который в шкале отмечен как -1

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#88]
**Шаги воспроизведения:**
1.	Авторизоваться как сотрудник  
2.	Перейти на вкладку Тест 
3.	Нажать Пройти тест 
4.	Нажать кнопку Назад 
5.	Снова нажать кнопку Назад несколько раз

**Фактический результат:**
Если в опроснике профессионального выгорания Маслач нажать Назад, окно опроса сворачивается в некликабельное окно, при последующим нажатии в этом окне на кнопку Назад вопросы появляются в обратном порядке с отрицательным числом в шкале, начиная с 21 вопроса (На работе я спокойно справляюсь с эмоциональными проблемами), который в шкале отмечен как -1 

**Ожидаемый результат:**
При нажатии кнопку Назад по логике должен быть возврат на страницу Тест 
Окружение: 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Критический

**Comment by QA-Aleksandra** [comment]
https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/488dd7aa-9fe7-450f-817c-18c7bf419fef

**Comment by RomanRiyanov** [comment]
Будет исправлено в следующей итерации

**Comment by RomanRiyanov** [comment]
Исправлено, будет видно сегодня вечером

**Comment by QA-Aleksandra** [comment]
исправлено
