### ISSUE TITLE
Если в три шкалы поставить ответы на вопросы в 1 балл, то шкала Редукция проф.достижений и Деперсонализация отображается с частью текста, если в три шкалы поставить ответы на вопросы в 0 баллов, отображение шкал с полным названием уровня

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#90]
**Шаги воспроизведения:**
1.	Авторизоваться как сотрудник  
2.	Перейти на вкладку Тест 
3.	Нажать Пройти тест, при ответах на вопросы отвечать на 1 вопрос (Очень редко), со 2 по 3 (Никогда), 4 и 5 вопрос отвечать (Очень редко) на 6 ой вопрос отвечать (Ежедневно), на остальные никогда
4.	Проверить результаты теста 
5.	Нажать Пройти тест, при ответах на 6 ой вопрос отвечать (Ежедневно), в остальных вопросах отвечать (Никогда)
6.	Проверить результаты теста
### Фактический результат:
Если в три шкалы поставить ответы на вопросы в 1 балл, то шкала Редукция проф.достижений и Деперсонализация отображается с частью текста, если в три шкалы поставить ответы на вопросы в 0 баллов, отображение шкал будет с полным названием уровня

**Ожидаемый результат:**
При отображении низкого уровня, не должна быть видна часть текста с названием уровня 
Окружение: 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Минорный

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/9c218200-d5cb-4b93-a98a-38eace684194)
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/822b4f87-e6c2-454c-8573-e6c9c8e745cb)

**Comment by RomanRiyanov** [comment]
Предположительно исправлено, так как воспроизвести повторно не удалось. Надо перепроверить

**Comment by QA-Aleksandra** [comment]
Если при ответах на 6 ой вопрос отвечать (Ежедневно), в остальных вопросах отвечать (Никогда), то получается везде 0 баллов. Если все во всех шкалах 0, наверное не должно быть вообще отображения ?
  "summary": {
                "graphs": [
                    {
                        "size": "big",
                        "color": "blue",
                        "title": "Значение индекса системного выгорания",
                        "value": 0.58,
                        "max_value": 1,
                        "min_value": 0
                    },
                    {
                        "size": "medium",
                        "text": "низкое",
                        "color": "green",
                        "title": "Эмоциональное истощение",
                        "value": 0,
                        "max_value": 54,
                        "min_value": 0
                    },
                    {
                        "size": "medium",
                        "text": "низкое",
                        "color": "green",
                        "title": "Личностное отдаление",
                        "value": 0,
                        "max_value": 30,
                        "min_value": 0
                    },
                    {
                        "size": "medium",
                        "text": "высокая",
                        "color": "red",
                        "title": "Редукция личных достижений",
                        "value": 0,
                        "max_value": 48,
                        "min_value": 0
                    }
                ]
            },
            "results": [
                {
                    "question_id": 11,
                    "variant_value": 0
                },
                {
                    "question_id": 12,
                    "variant_value": 0
                },
                {
                    "question_id": 13,
                    "variant_value": 0
                },
                {
                    "question_id": 14,
                    "variant_value": 0
                },
                {
                    "question_id": 15,
                    "variant_value": 0
                },
                {
                    "question_id": 16,
                    "variant_value": 6
                },
                {
                    "question_id": 17,
                    "variant_value": 0
                },
                {
                    "question_id": 18,
                    "variant_value": 0
                },
                {
                    "question_id": 19,
                    "variant_value": 0
                },
                {
                    "question_id": 20,
                    "variant_value": 0
                },
                {
                    "question_id": 21,
                    "variant_value": 0
                },
                {
                    "question_id": 22,
                    "variant_value": 0
                },
                {
                    "question_id": 23,
                    "variant_value": 0
                },
                {
                    "question_id": 24,
                    "variant_value": 0
                },
                {
                    "question_id": 25,
                    "variant_value": 0
                },
                {
                    "question_id": 26,
                    "variant_value": 0
                },
                {
                    "question_id": 27,
                    "variant_value": 0
                },
                {
                    "question_id": 28,
                    "variant_value": 0
                },
                {
                    "question_id": 29,
                    "variant_value": 0
                },
                {
                    "question_id": 30,
                    "variant_value": 0
                },
                {
                    "question_id": 31,
                    "variant_value": 0
                },
                {
                    "question_id": 32,
                    "variant_value": 0
                }
            ],
            "completion_date": "2023-06-23",
            "next_attempt_date": "2023-06-23"
        },

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/60176821-a17b-43e7-b608-702f5fc8ee56)

**Comment by RomanRiyanov** [comment]
"Если все во всех шкалах 0, наверное не должно быть вообще отображения?"

Я тут не соглашусь, пользователю интуитивно не понятно, что произошло - у него низкий уровень выгорания, или тест сломался и не выдает ничего? Если результаты теста хорошие и везде нули, я установил цветную заглушку на длину слова, чтобы видно было текст внутри, ровно как на скриншоте. Если ты всё-таки считаешь что должно быть пусто, давай может вынесем на обсуждение в чат

**Comment by QA-Aleksandra** [comment]
Да, я с тобой согласна, просто у нас в тз не написано какой ожидаемый результат, поэтому и спросила, все супер пусть будет так, только у нас при 0 отображается  шкала с полными названиями,  а при 1 балл, короткие с торчащими названиями ) я не знаю как тут быть )

**Comment by QA-Aleksandra** [comment]
это когда 1 все

![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/385e803f-b098-43fe-b341-ca83cb7bc456)

это когда 0

![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/01a0976a-6635-46ff-8b2e-85539468360b)

**Comment by QA-Aleksandra** [comment]
при 1 шкала должна быть длиннее по логике чем 0....

Получается, если мы принимаем за 0 отображение шкалы с полным названием, то все остальные результаты теста больше  0 должны отталкиваться от этой длины...

вот это вариант когда 4 и  по 2 балла в шкалах: 


![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/4ff8a92c-0077-4383-9b52-b1d28e39ab3d)


это 5 баллов: 


![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/c71248e2-d16b-470c-937e-8f114d31b6a5)



Это 0: 


![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/b298aeb1-6cd2-461d-b7b1-c14921df4864)

**Comment by RomanRiyanov** [comment]
Сделал минимальное значение по умолчанию - теперь не может быть меньше ширины текста внутри. Не должно) Остально пересчитывается так же, в процентах

**Comment by QA-Aleksandra** [comment]
результат ре-теста: баг исправлен, закрываю
