### ISSUE TITLE
Опросник имеет название Опросник профессионального выгорания Маслач, MBI/ПВ, состояние с большой буквы, название второй шкалы указано как Деперсонализация, название третей шкалы указано как  Редукция проф.достижений, ответ 5 имеет тест Очень часто, не указан номера вопроса, тексты описания Опросника, Результат при Нормальном, Тревожном, В группе риска, Рекомендации не соответствуют макету

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#91]
**Шаги воспроизведения:**
1.	Авторизоваться как сотрудник  
2.	Перейти на вкладку Тест 
3.	Нажать Пройти тест
4.	Проверить результаты теста 

**Фактический результат:**
1.	Опросник профессионального выгорания Маслач, MBI/ПВ
2.	Состояние с большой буквы 
3.	название второй шкалы указано как Деперсонализация 
4.	название третей шкалы указано как  Редукция проф.достижений 
5.	Ответ 5 Очень часто
6.	Нет номера вопроса 
7.	Тексты описания Опросника, Результат при Нормальном, Тревожном, В группе риска, Рекомендации не соответствуют макету 

**Ожидаемый результат:**
8.	Название Опросник профессионального выгорания Маслач
9.	Состояние с маленькой буквы
10.	название второй шкалы Личностное отдаление
11.	название третей шкалы Редукция личных достижений
12.	  {"text": " Почти всегда ", "value": 5 } 
13.	Есть номер вопроса, как в макете, например 1. Я чувствую себя эмоционально опустошенным/ой
14.	Тексты описания Опросника, Результат при Нормальном, Тревожном, В группе риска, Рекомендации соответствуют макету 

Окружение: 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Минорный

**Comment by RomanRiyanov** [comment]
Всё переименовано

**Comment by QA-Aleksandra** [comment]
осталось добавить номер вопроса в тесте 
и там текст чуть другой в шапке опроса после названия 
и еще текст после прохождения теста в результате

**Comment by QA-Aleksandra** [comment]
**Макет** 
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/74da830f-a0fa-4978-a737-d2e9d3e586f5)

**Реализация**
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/9928f4de-7786-425b-9e1f-33ca0efd6d15)

**Макет**  @AleksandrUsolcev 
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/4a0cc85d-38bd-4f5a-85d2-972b8c0f13c1)

**Comment by QA-Aleksandra** [comment]
Еще по первому опросу Экспресс-оценка выгорания в результатах после прохождения теста пока нет текстов @AleksandrUsolcev

**Comment by QA-Aleksandra** [comment]
@AleksandrUsolcev 
Новые макеты, которые в разработку после мвп Тест 1


![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/32b38c70-291b-4f36-ba2d-3a751fd04444)

**Comment by RomanRiyanov** [comment]
Нумерацию вопросов добавил.

Все опросы сделаны расширяемыми, поэтому никакие тексты не зашиты жёстко во фронтенд. Текста из заголовков и результатов тестов, рекомендации берутся с серверной части, где и происходит перерасчет результатов по формуле. Когда будем презентовать второй этап разработки, на бэке уже будет необходимая для отображения информация, кто будет её брать из учебников по психологии - я сказать затрудняюсь

**Comment by QA-Aleksandra** [comment]
По текстам я как раз для Саши писала, по заголовку в Тесте 2 и по результатам в Тесте 1, вот нашла как тегнуть в репорте) @AleksandrUsolcev
