### ISSUE TITLE
После прохождения теста результат имеет формулировку Экспресс-оценка выгорания вместо Опросник профессионального выгорания Маслач

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#92]
**Шаги воспроизведения:**
1.	Авторизоваться как сотрудник  
2.	Перейти на вкладку Тест 
3.	Нажать Пройти тест
4.	Проверить результаты теста 

**Фактический результат:**
После прохождения теста результат имеет формулировку Экспресс-оценка выгорания вместо Опросник профессионального выгорания Маслач

**Ожидаемый результат:**
После прохождения теста результат имеет формулировку Опросник профессионального выгорания Маслач

Окружение: 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Тривиальный

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/d7839fbd-283b-4a05-9764-806dab84faf0)
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/ec1901b1-3bcf-4ee7-8e98-c6c69854084a)

**Comment by RomanRiyanov** [comment]
Заголовки исправлены

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/12b11eff-65e2-434d-826a-662098d3ee15)

**Comment by QA-Aleksandra** [comment]
Вот тут еще нужно чуть поправить, новый баг-репорт создавать не буду, решила оставить комментарий к этому

**Comment by QA-Aleksandra** [comment]
исправлен, закрываю
