### ISSUE TITLE
В Mozilla Firefox варианты ответов на тест имеют точку рядом с названием

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#93]
**Шаги воспроизведения:**
1.	Авторизоваться как сотрудник  
2.	Перейти на вкладку Тест 
3.	Нажать Пройти тест
**Фактический результат:**
В Mozilla Firefox варианты ответов на тест имеют точку рядом с названием 

**Ожидаемый результат:**
В Mozilla Firefox варианты ответов на тест не имеют точку рядом с названием 

Окружение: 
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Тривиальный

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/da6d70a0-f0da-4815-b194-6d139d586919)

**Comment by RomanRiyanov** [comment]
Пока не получилось поправить, будет готово в следующей итерации

**Comment by RomanRiyanov** [comment]
Получилось поправить, будет видно сегодня вечером

**Comment by QA-Aleksandra** [comment]
исправлено
