### ISSUE TITLE
Зеленый цвет шкалы по результатам прохождения опроса в реализации #00b750, вместо  #99CA65, красный цвет шкалы по результатам опроса имеет #fa3d33, вместо #FF6941

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#94]
**Шаги воспроизведения:**
1.	Авторизоваться как сотрудник  
2.	Перейти на вкладку Тест 
3.	Нажать Пройти тест
**Фактический результат:**
Зеленый цвет шкалы по результатам прохождения опроса в реализации #00b750, вместо  #99CA65, красный цвет шкалы по результатам опроса имеет #fa3d33, вместо #FF6941

**Ожидаемый результат:**
Зеленый цвет шкалы по результатам прохождения опроса #99CA65, красный цвет шкалы по результатам опроса #FF6941

Окружение: 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Тривиальный

**Comment by RomanRiyanov** [comment]
Цвета исправлены

**Comment by QA-Aleksandra** [comment]
по красному проверила, по зеленой не могу проверить, так как теперь шкала идет без цвета

**Comment by QA-Aleksandra** [comment]
исправлен
