### ISSUE TITLE
В Mozilla Firefox варианты ответов на первый тест Экспресс-оценка выгорания имеют точку рядом с радиокнопкой

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#96]
**Шаги воспроизведения:**
1.	Авторизоваться как сотрудник
2.	Нажать Пройти Тест из Главной 

**Фактический результат:**
В Mozilla Firefox варианты ответов на первый тест Экспресс-оценка выгорания имеют точку рядом с радиокнопкой 

**Ожидаемый результат:**
В Mozilla Firefox варианты ответов на первый тест Экспресс-оценка выгорания имеют точку рядом с радиокнопкой 

**Окружение:**
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Тривиальный

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/086ea1fa-8c3d-41b2-890a-86592d5e0672)

**Comment by RomanRiyanov** [comment]
Исправил. Скрестил пальцы

**Comment by QA-Aleksandra** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/8d7742b9-e3e5-499a-9f5a-9a198a8ca7f6)

**Comment by QA-Aleksandra** [comment]
я куки, кэш все почистила, зарегала нового пользователя, все равно есть они ....

**Comment by QA-Aleksandra** [comment]
исправлен, закрываю
