### ISSUE TITLE
При нажатии на кнопку Подробнее, при отображении результатов, в состоянии открытого окна, остальные кнопки Подробнее с результатами тестов активны для нажатия

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#97]
**Шаги воспроизведения:**
1.	Авторизоваться как сотрудник  
2.	Перейти на вкладку Тест 
3.	Пройти тест
4.	Нажать Подробнее
5.	Нажать другие кнопки Подробнее для других тестов

**Фактический результат:**
При нажатии на кнопку Подробнее, при отображении результатов, в состоянии открытого окна, остальные кнопки Подробнее с результатами тестов активны для нажатия

**Ожидаемый результат:**
При нажатии на кнопку Подробнее, при отображении результатов, в состоянии открытого окна, остальные кнопки Подробнее с результатами тестов не активны для нажатия

Окружение: 
Браузеры: Chrome 113.0.5672.127, разрешение 1920х1080, ОС: Windows, 
Яндекс.Браузер 23.5.0.2271, разрешение 1920х1080, ОС: Windows,
Mozilla Firefox 113.0.2, разрешение 1920х1080, ОС: Windows.
Серьёзность бага: Минорный

**Comment by QA-Aleksandra** [comment]
Так как у нас в требованиях не прописано, я предполагаю это модальное окно, правильно я понимаю, что другие кнопки вне окна не должны быть активны для клика? Или может это не баг, а фича?) Если я не правильно поняла логику работы и так и должно быть то закрою баг. Подскажи, пожалуйста, должны ли быть другие кнопки активны для клика при открытом окне результата теста?

**Comment by QA-Aleksandra** [comment]
https://github.com/AcceleratorYandexPracticum/employee_mood/assets/132297195/8f8263a6-c47e-424c-a84a-84e93b740dbd

**Comment by RomanRiyanov** [comment]
Исправлено, результаты тестов растягиваются больше, кнопки ПОДРОБНЕЕ под ними - disabled.

**Comment by QA-Aleksandra** [comment]
сделала повторное тестирование, все также не disabled .....

**Comment by QA-Aleksandra** [comment]
исправлено, закрываю
