### ISSUE TITLE
Ошибка 500 Internal Server Error вместо 204 при отправке запроса DELETE/socials/likes/{id}/

### ISSUE THREAD

**Issue by QA-Aleksandra** [AcceleratorYandexPracticum/employee_mood#98]
**Окружение:**
https://em-test.usolcev.com/api/v1/swagger/

**Шаги воспроизведения:**

1.	создать пользователя 
2.	создать мероприятие от имени HR 
3.	создать токен для пользователя
4.	поставить лайк данному мероприятию под токеном пользователя POST/socials/likes/
5.	Получить id лайка в ответе
{
    "id": 3,
    "created": "2023-06-26T16:05:17.309785+03:00",
    "event": 7,
    "entry": null
}

6.	проверить через GET https://em-test.usolcev.com/api/v1/events/?liked=true под токеном пользователя что лайк есть 
    "results": [
        {
            "id": 7,
            "liked": {
                "id": 3,
                "created": "2023-06-26T16:05:17.309785+03:00"
            },

7.	отправить DELETE/socials/likes/3/
}

**Фактический результат:**
500 Internal Server Error 
<!doctype html>
<html lang="en">

<head>
	<title>Server Error (500)</title>
</head>

<body>
	<h1>Server Error (500)</h1>
	<p></p>
</body>

</html> 

**Ожидаемый результат:**
204

**Comment by QA-Aleksandra** [comment]
16:13:31 ERROR [21] django.request: Internal Server Error: /api/v1/socials/likes/3\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/asgiref/sync.py\", line 486, in thread_handler\n    raise exc_info[1]\n  File \"/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py\", line 42, in inner\n    response = await get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asgiref/sync.py\", line 486, in thread_handler\n    raise exc_info[1]\n  File \"/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py\", line 253, in _get_response_async\n    response = await wrapped_callback(\n               ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asgiref/sync.py\", line 448, in __call__\n    ret = await asyncio.wait_for(future, timeout=None)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/tasks.py\", line 442, in wait_for\n    return await fut\n           ^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py\", line 22, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asgiref/sync.py\", line 490, in thread_handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py\", line 125, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py\", line 90, in destroy\n    instance = self.get_object()\n               ^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/generics.py\", line 99, in get_object\n    self.check_object_permissions(self.request, obj)\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 345, in check_object_permissions\n    if not permission.has_object_permission(request, self, obj):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/permissions.py\", line 64, in has_object_permission\n    self.op2.has_object_permission(request, view, obj)\n  File \"/app/api/v1/permissions.py\", line 67, in has_object_permission\n    or request.user.is_authenticated and request.user == obj.author\n                                                         ^^^^^^^^^^\nAttributeError: 'Like' object has no attribute 'author'\n"

**Comment by AleksandrUsolcev** [comment]
https://github.com/moodbeat/back/pull/8

**Comment by QA-Aleksandra** [comment]
результат ре-теста: баг исправлен, закрываю
